---
- hosts: webserver
  vars:
    http_port: 80
  remote_user: lxg
  tasks:
    - name: test connection
      ping:
      remote_user: lxg
    - name: check nginx version
      command: nginx -V
    
